# Generated by Django 6.0.1 on 2026-03-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_message_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
